### ISSUE TITLE
unicode?

### ISSUE THREAD

**Issue by crackfed** [pedromagician/CMD_MessageBoxEx#1]
Can't seem to embed Unicode chrs even with a font that supports it (Code2000 for ex.) Found this, it might be useful.

https://nolongerset.com/unicode-friendly-msgbox/

**Comment by pedromagician** [comment]
Unicode worked. Now it also accepts \u{...}
![mbox](https://user-images.githubusercontent.com/64585665/213275778-0b3fa444-52eb-4924-b53a-dfe626934f09.png)
