### ISSUE TITLE
blue 'working' ring

### ISSUE THREAD

**Issue by crackfed** [pedromagician/CMD_MessageBoxEx#3]
I might have brought this up before but but it's still an issue. When MessageboxEX starts, if the mouse cursor is over the BMP image or is moved there right away, it is displayed as a rotating blue 'working' ring and will appear that way indefinitely. However, if it is moved to just beyond any edge of the window for some minimum amount of time (maybe 100ms?) then it becomes a normal looking mouse cursor. By moving it to the window edge something is triggered to cancel the blue ring. I have occasionally seen the blue ring appear with other apps but it always returns to normal on its own without having to move the cursor outside of a window briefly. This is Win 11 and MBEX 7.5 and previous versions.

**Comment by pedromagician** [comment]
I added cursor settings. Try a newer version.

**Comment by crackfed** [comment]
Works perfect. ty.
